// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands.Drives;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.RobotContainer;
import frc.robot.Constants.*;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.DriveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Drive extends CommandBase {


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private final DriveTrain m_driveTrain;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public Drive(DriveTrain subsystem) {


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS;
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_driveTrain = subsystem;
        addRequirements(m_driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        //For Xbox Controller
        m_driveTrain.setDrive(
        MathUtil.applyDeadband(-RobotContainer.getInstance().getdriverController().getLeftY()
         * m_driveTrain.getDriveLockLR(),OIConstants.kDriveDeadband), 
        MathUtil.applyDeadband(-RobotContainer.getInstance().getdriverController().getLeftX()
         * m_driveTrain.getDriveLockFR(),OIConstants.kDriveDeadband), 
        MathUtil.applyDeadband(-RobotContainer.getInstance().getdriverController().getRightX()
         * m_driveTrain.getRotationLock(), OIConstants.kTurnDeadband), 
        m_driveTrain.getFieldOriented(),false); //Not robot oriented drive, field oriented
        SmartDashboard.putNumber("Drive LR Lock Value", m_driveTrain.getDriveLockLR());
        SmartDashboard.putNumber("Drive FR Lock Value", m_driveTrain.getDriveLockFR());
        SmartDashboard.putNumber("Rotation Lock Value", m_driveTrain.getRotationLock());

        // //For Joystick
        // m_driveTrain.setDrive(
        // MathUtil.applyDeadband(-RobotContainer.getInstance().getJoystick1().getY()
        //  * m_driveTrain.getDriveLockLR(),OIConstants.kDriveDeadband), 
        // MathUtil.applyDeadband(-RobotContainer.getInstance().getJoystick1().getX()
        //  * m_driveTrain.getDriveLockFR(),OIConstants.kDriveDeadband), 
        // MathUtil.applyDeadband(-RobotContainer.getInstance().getJoystick1().getTwist()
        //  * m_driveTrain.getRotationLock(), OIConstants.kDriveDeadband), 
        // m_driveTrain.getFieldOriented(),m_driveTrain.getSlew()); //Not robot oriented drive, field oriented
        // SmartDashboard.putNumber("Drive LR Lock Value", m_driveTrain.getDriveLockLR());
        // SmartDashboard.putNumber("Drive FR Lock Value", m_driveTrain.getDriveLockFR());
        // SmartDashboard.putNumber("Rotation Lock Value", m_driveTrain.getRotationLock());
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        // m_driveTrain.setDrive(0.0, 0.0, 0.0,m_driveTrain.getFieldOriented());
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
