// // RobotBuilder Version: 5.0
// //
// // This file was generated by RobotBuilder. It contains sections of
// // code that are automatically generated and assigned by robotbuilder.
// // These sections will be updated in the future when you export to
// // Java from RobotBuilder. Do not put any code or make any change in
// // the blocks indicating autogenerated code or it will be lost on an
// // update. Deleting the comments indicating the section will prevent
// // it from being updated in the future.

// // ROBOTBUILDER TYPE: Subsystem.

// package frc.robot.subsystems;


// import frc.robot.commands.*;
// import edu.wpi.first.wpilibj.livewindow.LiveWindow;
// import edu.wpi.first.wpilibj2.command.SubsystemBase;
// import edu.wpi.first.wpilibj.PWM.*;
// import edu.wpi.first.wpilibj.Servo;
// // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


// /**
//  *
//  */
// public class ServoSub extends SubsystemBase {
//     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
//     private Servo m_servo;
//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

//     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
//     /**
//     *
//     */
//     public ServoSub(int channel) {
//         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//         m_servo = new Servo(1);
//         addChild("Servo", m_servo);
//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//     }

//     public void servo180(){
//         m_servo.setAngle(180);
//     }
//     public void servo0(){
//         m_servo.setAngle(0);
//     }

//     @Override
//     public void periodic() {
//         // This method will be called once per scheduler run
        
//     }

//     @Override
//     public void simulationPeriodic() {
//         // This method will be called once per scheduler run when in simulation

//     }

//     // Put methods for controlling this subsystem
//     // here. Call these from Commands.

// }

