// // RobotBuilder Version: 5.0
// //
// // This file was generated by RobotBuilder. It contains sections of
// // code that are automatically generated and assigned by robotbuilder.
// // These sections will be updated in the future when you export to
// // Java from RobotBuilder. Do not put any code or make any change in
// // the blocks indicating autogenerated code or it will be lost on an
// // update. Deleting the comments indicating the section will prevent
// // it from being updated in the future.

// // ROBOTBUILDER TYPE: Subsystem.

// package frc.robot.subsystems;


// import frc.robot.commands.*;
// import edu.wpi.first.wpilibj.livewindow.LiveWindow;
// import edu.wpi.first.wpilibj2.command.SubsystemBase;
// import edu.wpi.first.wpilibj.Servo.*;
// import edu.wpi.first.wpilibj.PWM.*;
// // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


// /**
//  *
//  */
// public class Servo extends SubsystemBase {
//     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

//     // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//     private Servo servo = new Servo(1);

//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
//     /**
//     *
//     */
//     public Servo(int channel) {
//         // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    
//     addChild("Servo", servo);
//     // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//     }

//     public void spinServo(){
//         servo.
//     }

//     @Override
//     public void periodic() {
//         // This method will be called once per scheduler run
        
//     }

//     @Override
//     public void simulationPeriodic() {
//         // This method will be called once per scheduler run when in simulation

//     }

//     // Put methods for controlling this subsystem
//     // here. Call these from Commands.

// }

