// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands.Auton;
import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;

import java.util.function.DoubleSupplier;
import com.pathplanner.lib.PathPlanner;
import com.pathplanner.lib.PathConstraints;
import com.pathplanner.lib.PathPlannerTrajectory;
import java.util.HashMap;
import edu.wpi.first.wpilibj2.command.Command;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Arm;
import frc.robot.subsystems.DriveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class ApproachGrid extends SequentialCommandGroup {


    public ApproachGrid(DriveTrain subsystem) {
        

        PathPlannerTrajectory appGrid = PathPlanner.loadPath("Approach Grid", new PathConstraints(0.33, 0.33));
        addCommands(
            //Arm up to high node then open arm then follow trajectory.
            //Ideally the arm goes down during the trajectory, still needs testing.
            subsystem.followTrajectoryCommand(appGrid, true)
        );
    }
}
